[tool.black]
exclude = '''
    /(
          \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | dist
    )/
    '''
include = '\.py$'
line-length = 99
target-version = ['py38']

[tool.isort]
combine_as_imports = true
line-length = 99
profile = "black"
